# Change these first
owner: ThomasGerr # Your GitHub organization or username, where this repository lives
repo: ethicbyte_upptime # The name of this repository

sites:
  - name: Ethicbyte website
    url: https://www.ethicbyte.nl
  - name: Persoonlijke website Thomas Gerrits
    url: https://www.thomasgerrits.nl
  - name: Nowayste escapes
    url: https://www.nowayste-escapes.nl
  - name: youtube.com
    url: https://www.youtube.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /ethicbyte_upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Ethicbyte uptime monitor and status page."
  introMessage: Live statussen van ethicbyte services.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
